MedPipe3D_JSOC_proposal
JuliaLang/www.julialang.org pull request #2014
Opened 2024-01-11 17:32 UTC by jakubMitura14

Adding JSOC proposal. Suggested reviewer Jacob Zelko

2024-01-11 17:40 UTC, jakubMitura14 reviewed
> Adding JSOC proposal. Suggested reviewer Jacob Zelko 

@TheCedarPrince Cedar prince do not display on ossible reviewer list

2024-01-14 18:37 UTC, TheCedarPrince requested changes
This looks fantastic! Left some comments/suggestions. The biggest comment is just the first comment -- feel free to integrate or reject the others as you see fit. Exciting! :smile:

2024-01-14 18:37 UTC, TheCedarPrince commented on jsoc/gsoc/medpipe3d.md
> +MedPipe3D.jl together with MedEye3D.jl MedEval3D.jl and currently in development MedImage.jl is a set of libraries created to provide essential tools for 3D medical imaging to the Julia language ecos
Some comments on this piece: 

1. Could you link the repositories here for each package you mentioned?
2. Could you make a markdown list to explain what (in just a few words) what each package does generally?
3. I'd remove the line about package migration.

2024-01-14 18:37 UTC, TheCedarPrince commented on jsoc/gsoc/medpipe3d.md
Could you actually make the PR against this file: https://github.com/JuliaLang/www.julialang.org/blob/c35d1b42090ce631a46a221996446d3ecc9c6700/jsoc/gsoc/juliahealth.md?plain=1 ?

And then add a section for the Medical Imaging Subecosystem with the projects you have here listed underneath it?

2024-01-14 18:37 UTC, TheCedarPrince commented on jsoc/gsoc/medpipe3d.md
> +  - Some experience with 3d volumetric data with spatial metadata (or a willingness to learn!)
Just a suggestion, but in the past, students have found it helpful when I list what packages to be familiar with as well as any links to requisite background knowledge (youtube videos, articles, etc.). Might want to consider adding them in.

2024-01-14 18:37 UTC, TheCedarPrince commented on jsoc/gsoc/medpipe3d.md
> +MedPipe3D was created as a package that improves integration between other parts of the small ecosystem (MedEye3D, MedEval3D, and MedImage). Currently, it needs to be expanded and adapted so it can b
Could you expand this description further to say in what ways it needs to be expanded/adapted?

2024-01-14 18:37 UTC, TheCedarPrince commented on jsoc/gsoc/medpipe3d.md
> +For each point mentor will also supply the person responsible for implementation with examples of required functionalities in Python or will point to the Julia libraries already implementing it (that
Remove line?

2024-01-25 20:41 UTC, TheCedarPrince approved these changes

2024-01-25 20:44 UTC, merged