KomaMRI Proposal for JSoC
JuliaLang/www.julialang.org pull request #2020
Opened 2024-01-17 19:54 UTC by beorostica

We are thrilled to participate in JSoC/GSoC. This is our proposal.

2024-01-17 20:05 UTC, cncastillo commented on jsoc/gsoc/juliahealth.md
> +Simulations can help to grasp hard-to-understand MRI concepts, like signal acquisition, and image reconstruction. Moreover, they can guide the design of novel pulse sequences, and generate synthetic
```suggestion
KomaMRI.jl is a Julia package designed for highly-efficient Magnetic Resonance Imaging (MRI) simulations, serving both educational and research purposes. Simulations can help to grasp hard-to-understand MRI concepts, like signal acquisition, and image reconstruction. Moreover, they can guide the design of novel pulse sequences, and generate synthetic data for training machine learning models.
```
Thanks @beorostica for the PR, I think these can be in the same paragraph.

2024-01-19 16:55 UTC, TheCedarPrince commented
Could you give me review permissions here @ViralBShah ? I was going to make a review but realized I couldn't be requested as a reviewer. Thanks!

2024-01-19 16:57 UTC, ViralBShah commented
Invited.

2024-01-19 16:59 UTC, TheCedarPrince commented
Awesome -- I'll take a look in a couple hours. Thanks @ViralBShah!

2024-01-19 17:02 UTC, giordano commented
> I was going to make a review but realized I couldn't be requested as a reviewer. Thanks!

For what is worth, you don't need to be a collaborator of a repository to do a review.  @cncastillo did a review above for example.

2024-01-25 20:53 UTC, TheCedarPrince requested changes
Once you address my small comment and also fix the merge conflict (this should go under the "Medical Imaging Subecosystem Projects" section) this will be ready to merge. Thanks @beorostica

2024-01-25 20:53 UTC, TheCedarPrince commented on jsoc/gsoc/juliahealth.md
> +- **Duration:** 320 hours (2 months, 8 hours per day)
Could you change this to 350 hours?

2024-01-25 21:19 UTC, beorostica commented on jsoc/gsoc/juliahealth.md
> +- **Duration:** 320 hours (2 months, 8 hours per day)
Addressed in a899540 and  7a8c199

2024-01-25 21:23 UTC, merged